version: "3.7"
services:
  db:
    container_name: db
    image: mysql
    # command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    # volumes:
    #   - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: people
    networks:
      - backend
  app:
    container_name: app
    build: app
    restart: on-failure
    depends_on:
      - db
    networks:
      - backend
      - frontend
  web:
    container_name: web
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontend
# volumes:
#     db-data:
networks:
  backend:
  frontend:
