version: "3.5"
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: people
    networks:
      - backend
  flask:
    container_name: flask
    build: app
    restart: on-failure
    expose:
      - 5000
    depends_on:
      - db
    networks:
      - backend
      - frontend
  web:
    container_name: proxy
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/ssl:/etc/nginx/ssl
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
networks:
  backend:
  frontend:
